language: ruby
rvm:
  - 2.1.5
bundler_args: --without development
before_install: gem install bundler, '~> 1.9'
branches:
  only:
      - master
  email:
    - diapriid@gmail.com 
  on_failure: change
